plugins {
    id 'com.android.application'
}

android {
    namespace 'com.livetgtv.embedtv'
    compileSdk 35

    defaultConfig {
        applicationId 'com.livetgtv.embedtv'
        minSdk 23
        targetSdk 28
        versionCode 2
        versionName '2.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
